name: Playwright-Elixir CI

on:
  push:
    branches: [ 20210610-ci-setup ]
  pull_request:
    branches: [ main ]

jobs:
  all:
    name: Build & Test
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    services:
      playwright:
        image: docker.io/geometer/playwright-proxy:latest
        ports:
          - 3000:3000
          - 8080:8080
        options: "-it --ipc=host"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.12.0'
        otp-version: '24.0.1'
    # - name: Restore dependencies cache
    #   uses: actions/cache@v2
    #   with:
    #     path: deps
    #     key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    #     restore-keys: ${{ runner.os }}-mix-
    - name: Install Elixir dependencies
      run: mix deps.get
    - name: Install Node dependencies
      run: npm install --prefix assets
    - name: Run tests
      run: mix test test/example_test.exs
